export let rows = [
  {
    id: 1,
    lastName: "Snow",
    firstName: "Jon",
    age: 35,
    gender: "Male",
    contact: 9876543210,
    category: "A",
    height: "170cm",
    weight: "60kg",
  },
  {
    id: 2,
    lastName: "Lannister",
    firstName: "Cersei",
    age: 42,
    gender: "Female",
    contact: 9876543210,
    category: "B",
    height: "160cm",
    weight: "70kg",
  },
  {
    id: 3,
    lastName: "Lannister",
    firstName: "Jaime",
    age: 45,
    gender: "Male",
    contact: 9876543210,
    category: "A",
    height: "170cm",
    weight: "60kg",
  },
  {
    id: 4,
    lastName: "Stark",
    firstName: "Arya",
    age: 16,
    gender: "Male",
    contact: 9876543210,
    category: "A",
    height: "170cm",
    weight: "60kg",
  },
  {
    id: 5,
    lastName: "Targaryen",
    firstName: "Daenerys",
    age: 24,
    gender: "Male",
    contact: 9876543210,
    category: "A",
    height: "170cm",
    weight: "60kg",
  },
  {
    id: 6,
    lastName: "Melisandre",
    firstName: "Quin",
    age: 50,
    gender: "Male",
    contact: 9876543210,
    category: "A",
    height: "170cm",
    weight: "60kg",
  },
  {
    id: 7,
    lastName: "Clifford",
    firstName: "Ferrara",
    age: 44,
    gender: "Male",
    contact: 9876543210,
    category: "A",
    height: "170cm",
    weight: "60kg",
  },
  {
    id: 8,
    lastName: "Frances",
    firstName: "Rossini",
    age: 36,
    gender: "Male",
    contact: 9876543210,
    category: "A",
    height: "170cm",
    weight: "60kg",
  },
  {
    id: 9,
    lastName: "Roxie",
    firstName: "Harvey",
    age: 65,
    gender: "Male",
    contact: 9876543210,
    category: "A",
    height: "170cm",
    weight: "60kg",
  },
  {
    id: 10,
    lastName: "Roxie",
    firstName: "Harvey",
    age: 65,
    gender: "Male",
    contact: 9876543210,
    category: "A",
    height: "170cm",
    weight: "60kg",
  },
];
